# -*- coding: utf-8 -*-
"""Data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxteG_kDeXRgSkOxBiv9x_Hx3VkbBJBz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# importing the dataset
df = pd.read_csv('/content/dirty_cafe_sales.csv')

df.head()

#Number of Rows: 10,000
#Number of Columns: 8
df.shape

""" basic information **checking**"""

# shows column names & data types
df.info()

# summary (mean, min, max)
df.describe()

"""Checking of the data types"""

df.dtypes

"""here in the dataset object refers to text/string data"""

# converting of columns to numeric data
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")


# converting Transaction Date	to corrected date column
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce")

df.dtypes

"""**Check for Missing Values**"""

df.isnull().sum()

# showing null values using matplot
df.isnull().sum().plot(kind="bar")
plt.title("Number of Null Values")
plt.xlabel("Columns")
plt.ylabel("Number of Null Values")
plt.show()

"""Fill missing values column-by-column using the median"""

for col in df.columns:
    # Fill numeric columns with their median
    if pd.api.types.is_numeric_dtype(df[col]):
        df[col].fillna(df[col].median(), inplace=True)
    # Fill object (string/categorical) columns with their mode
    elif df[col].dtype == 'object':
        # .mode() returns a Series, so we take the first element
        df[col].fillna(df[col].mode()[0], inplace=True)

# Handle 'Transaction Date' separately, as it's a datetime type
# Fill missing 'Transaction Date' values with the mode (most frequent date)
if 'Transaction Date' in df.columns and df['Transaction Date'].isnull().any():
    # Only fill if there are missing values to avoid errors if mode is empty
    mode_date = df['Transaction Date'].mode()[0]
    df['Transaction Date'].fillna(mode_date, inplace=True)

# checking again for missing values
df.isnull().sum()

df.duplicated().sum()

"""Identify Outliers (Boxplot)


Outliers are data points that are significantly different from the rest of the values in a dataset.

Outliers appear due to:

Data entry mistakes
Example: Writing 500 instead of 50.

Measurement errors
Example: Faulty machine reading.

Genuine extreme behavior
Example: One day, someone buys 20 coffees instead of 1 or 2.
"""

plt.boxplot(df['Price Per Unit'])
plt.title("Price Outliers")
plt.show()

plt.boxplot(df['Quantity'])
plt.title("Quantity Outliers")
plt.show()

plt.boxplot(df['Total Spent'])
plt.title("Total Spent Outliers")
plt.show()

"""✅ Conclusion

“There are no outliers in the Quantity, Price Per Unit, or Total Spent columns, as all values fall within the IQR range and no points appear outside the whiskers in the boxplots.
"""

