# -*- coding: utf-8 -*-
"""DataCleaningWithPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXmCOEZORTeRLorTn0A_QQwmL_QEVWII
"""

import numpy as np
import pandas as pd
df = pd.read_csv('/content/marketing_campaign_data_messy.csv')
print(f"Loaded Dataset : {df.shape[0]} rows, {df.shape[1]} columns")

df

df.tail()

df.head()

print(df.columns.tolist())
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
print("FIX APPLIED")
print(df.columns.tolist())

dirty_spend_mask = df['spend'].astype(str).str.contains(r'\$')
print(df.loc[dirty_spend_mask, ['campaign_id','spend']].head(3))

