# -*- coding: utf-8 -*-
"""datamanipuation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5sJAvWBgYPpZp22Ive3n4TEoqBObQ_K
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Student.csv")

df.head()

df.tail()

df.head(10)

df.info()

df.columns

df.describe()

df.isna()

df.isna().sum()

df.min()

df.max()

df.drop(index=0,axis=0)

df.head(1)

df1 = df.copy()

df.isna().sum()

df1['marks'] = df1['marks'].fillna(df1['marks'].mean())

df.iloc[1]

df1.iloc[2:5]

df.iloc[2:5]

df1.iloc[0]

df2 = df.copy()

df2.iloc[2:3]

df2['marks'] = df2['marks'].fillna(df2['marks'].mean())

df2.isna().sum()

df3 = df.copy()

df3['marks'].mode()

df3['marks'] = df3['marks'].fillna(df3['marks'].mode()[1])

df3.iloc[2]

df.isna().sum()

df4 = df.copy()

df4.isna().sum()

df4.isnull().sum()

df5 = df4.copy()

df5['attendance'] = df5['attendance'].fillna(0)

df5['marks'] = df5['marks'].fillna(0)

df.iloc[2]

df5.iloc[2]

df4.iloc[1:10]

df4['marks'] = df4['marks'].fillna(df4['marks'].ffill())

df4.iloc[1:10]

df4['attendance'] = df4['attendance'].fillna(df4['attendance'].bfill())

df4.iloc[1:10]

df4.iloc[:]

new_df = df[df['marks']>70]

df[df['marks']>90]

new_df.iloc[:]

df[(df['marks']>65) & (df['attendance']>70)]

square = lambda x : x*x

print(square(5))

gst = lambda amount : amount+(amount*0.18)

print(gst(2000))

even_or_odd = lambda x : 'even' if x%2==0 else 'odd'

print(even_or_odd(5))

salaries=[10000,20000,30000]
inc_sal=[]
for s in salaries:
  inc_sal.append(s+(s*0.10))
print(inc_sal)

salaries=[10000,20000,30000]
inc_sal=[s+(s*0.10) for s in salaries ]
print(inc_sal)

salaries = [10000, 20000, 30000]
inc_sal = (map(lambda x: x+(x*0.10), salaries))
print(inc_sal)

salaries = [10000, 20000, 30000]
inc_sal = list(map(lambda x: x+(x*0.10), salaries))
print(inc_sal)

df.dropna()

df['result'] = df['marks'].apply(lambda x : 'pass' if x>=60 else 'fail')

df.columns

df.drop('result',axis=1)

