# -*- coding: utf-8 -*-
"""HandleMissingValues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFVkTfFwL5cR74LVghnhnccAxqNchO8Y

methods to handle missing values:
1. imputation
2. dropping
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading the dataset to a pandas DataFrame
dataset = pd.read_csv('/content/Placement_Dataset.csv')

dataset.head()

dataset.shape

dataset.isnull().sum()
# gives the null values in all the columns in the dataset

"""Central Tendencies:
1. Mean
2. Mode
3. Median

"""

# analyze the distribution of data in the salary
fig, ax = plt.subplots(figsize=(8,8))
sns.distplot(dataset.salary)

"""replacing the missing values with median values"""

dataset['salary'].fillna(dataset['salary'].median(numeric_only=True))

dataset.isnull().sum()

# filling the missing values with mean values
dataset['salary'].fillna(dataset['salary'].mean(numeric_only=True))

dataset['salary'].fillna(dataset['salary'].mode(),inplace=True)

dataset.isnull().sum()

"""Dropping Method"""

salary_dataset = pd.read_csv('/content/Placement_Dataset.csv')

# Dropping Method
salary_dataset=salary_dataset.dropna(how='any')

salary_dataset.isnull().sum()

