# -*- coding: utf-8 -*-
"""mathsinml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAD3nDcGWxF1ARuKLmJenBatUVq1cQq6
"""

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

plt.quiver(0,0,4,5)
plt.show()

plt.quiver(0,0,4,5,angles='xy',scale_units='xy',scale=1)
plt.xlim(0,8)
plt.ylim(0,8)
plt.show()

plt.quiver(-8,8,4,5,angles='xy',scale_units='xy',scale=1,color='g')
plt.quiver(-8,8,-1,-5,angles='xy',scale_units='xy',scale=1,color='r')
plt.xlim(-20,20)
plt.ylim(-20,20)
plt.grid(True)
plt.show()