# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147rj2UKoLvVjT3rYklcbGx9DuVy3zAGa

matplotlib :
1. used for making plots
"""

# importing matplotlib library
import matplotlib.pyplot as plt

# import numpy
import numpy as np

x = np.linspace(0,10,100)
y = np.sin(x)
z = np.cos(x)

print(x)

print(y)

print(z)

"""plotting the data"""

# sine wave
plt.plot(x,y)
plt.show()

plt.plot(x,z)
plt.show()

plt.plot(y,z)
plt.show()

# adding title and labels to x and y axis
plt.plot(x,y)
plt.xlabel('angle')
plt.ylabel('sine value')
plt.title('sine wave')
plt.show()

#parabola
x = np.linspace(-10,10,20)
y = x**2
plt.plot(x,y)
plt.show()

plt.plot(x,y, 'r+')
plt.show()

plt.plot(x,y, 'g.')
plt.show()

plt.plot(x,y, 'rx')
plt.show()

plt.plot(x,y, 'b*')
plt.show()

x = np.linspace(-5,5,50)
plt.plot(x, np.sin(x), 'y-')
plt.plot(x, np.cos(x), 'r--')
plt.show()

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
language = ['java', 'python', 'c++', 'ruby', 'c']
students = [23,17,35,29,12]
ax.bar(language, students)
plt.xlabel('language')
plt.ylabel('number of students')
plt.show()

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
people=[100,150,200,250,300]
language = ['java', 'python', 'c++', 'ruby', 'c']
ax.pie(people,labels=language,autopct='%1.1f%%')
plt.show()

x=np.linspace(0,10,30)
y=np.sin(x)
z=np.cos(x)
fig2 = plt.figure()
ax2 = fig2.add_axes([0,0,1,1])
ax2.scatter(x,y,color='r')
ax2.scatter(x,z,color='b')
plt.show()

fig = plt.figure()
ax = plt.axes(projection='3d')
z = 20*np.random.random(100)
x = np.sin(z)
y = np.cos(z)
ax.scatter(x,y,z,c=z,cmap='Greens')
plt.show()

