# -*- coding: utf-8 -*-
"""pandasbasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7CH1J33JEF5ifudlvXSNoa8YOlrjcUA
"""

#pandas library:

#used for data processing, manipulation and analysis

#pd dataframe :

#pd data frame is two dimensional tabular data frame structure with labelled access(rows and column)

# importing pandas library
import pandas as pd
import numpy as np

# importing the boston house price data
from sklearn.datasets import fetch_california_housing

california_dataset = fetch_california_housing()

from sklearn.datasets import fetch_california_housing
california_dataset = fetch_california_housing()
type(california_dataset)

print(california_dataset)

cal_df = pd.DataFrame(california_dataset.data, columns = california_dataset.feature_names)
#dataframes are used to make the rough data into beautiful tables with values inside the tables

print(cal_df)

cal_df.head()

cal_df.shape

type(cal_df)

"""importing the data from csv file to pandas df"""

# csv file to pandas df
diabetes_df = pd.read_csv("/content/diabetes_dataset.csv")

type(diabetes_df)

diabetes_df.head()

diabetes_df.shape

"""exporting dataframe to a csv file

loading the data from excel file to pandas dataframe :
diabetes_df = pd.read_excel('file path')
"""

cal_df.to_csv('california_csv')

"""exporting pandas dataframe into an excel file :
df.to_excel('file name')
"""

cal_df.to_excel('california_excel.xlsx')

# creating a DataFrame with random values (for random values we need numpy also)
random_df = pd.DataFrame(np.random.rand(20,10))

random_df.head()

random_df.shape

"""Inspecting a df"""

#getting number of rows and columns
cal_df.shape

# getting first 5 rows
cal_df.head()

# getting last 5 rows
cal_df.tail()

# information of the data set
cal_df.info()

cal_df.all

print(cal_df)

# used to find number of null values in each column
cal_df.isnull().sum()

diabetes_df.head()

# counting the values based on labels
diabetes_df.value_counts('target')

print(diabetes_df)

# group the rows values based on the mean
diabetes_df.groupby('target').mean()

"""statistical measures"""

# count or number of values in each column
cal_df.count()

# mean value - each column
cal_df.mean()

# standard deviation of each column
cal_df.std()

# minimum value in each column
cal_df.min()

# maximum value in each column
cal_df.max()

# all the statistical measues of a dataframe
cal_df.describe()

print(california_dataset)

"""manipulating the dataframe"""

# adding a column to a dataframe
cal_df['price'] = california_dataset.target

cal_df.head()

#removing a particular row
cal_df.drop(index = 0, axis = 0)

# removing a particular column
cal_df.drop(columns='AveRooms', axis=0)

#printing a particular row using index value
cal_df.iloc[2]

# printing or locating a particular column
print(cal_df.iloc[:,0]) # first column
print(cal_df.iloc[:,1]) # second column
print(cal_df.iloc[:,2]) # third column

"""correlations :
1. postive correlation
2. negative correlation
"""

cal_df.corr()