# -*- coding: utf-8 -*-
"""train-test-split.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sn87ueM6C9k3lMOGdlfATxNZ1xVs_7qz
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data collection and analysis<br>
PIMA DIABETES DATASET


"""

dsds = pd.read_csv('/content/diabetes.csv')

dsds.head()

dsds.shape

dsds.describe()

dsds['Outcome'].value_counts()

"""0 --> non diabetic
<br>
1 --> diabetic
"""

dsds.groupby('Outcome').mean()

X = dsds.drop(columns = 'Outcome', axis=1)
Y = dsds['Outcome']

print(X)

print(Y)

scaler = StandardScaler()

scaler.fit(X)

s_data = scaler.transform(X)

X = s_data
Y = dsds['Outcome']

print(X)
print(Y)

"""splitting the data into training data and testing data"""

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state= 2)

print(X.shape, X_train.shape, X_test.shape)

